TeamManagmentTool/Controllers/ContestsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TMT.Core.Models.Contests;
using TMT.Core.Models;
using TMT.Core.DataManagers;

namespace TeamManagmentTool.Controllers
{
    [Authorize]
    public class ContestsController : BaseController
    {
        public ContestsController(IDataManager dataManager)
        {
            base.dataManager = dataManager;
        }

        public ActionResult Index()
        {
            IEnumerable<Contest> contests = DataManager.GetContests();
            return View(contests);
        }

        [HttpGet]
        public ActionResult Create()
        {
            ViewBag.SubmitAction = "Create";
            ViewBag.ActionTitle = "Create contest";
            return View(new ContestCreateModel(UserId));
        }

        [HttpPost]
        public ActionResult Create(ContestCreateModel model)
        {
            Contest contest = model.ToContest();
            DataManager.CreateContest(contest);
            for (int i = 0; i < model.ProblemsCount; ++i )
            {
                DataManager.CreateProblem(new Problem
                {
                    ContestId = contest.Id,
                    Solved = false,
                    Comments = "",
                    ProblemId = i,
                    Date = DateTime.Now
                });
            }
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Edit(int contestId)
        {
            ViewBag.SubmitAction = "Edit";
            ViewBag.ActionTitle = "Edit contest";
            return View("Create", new ContestCreateModel(DataManager.GetContests().First(c => c.Id == contestId)));
        }

        [HttpPost]
        public ActionResult Edit(ContestCreateModel model)
        {
            Contest contest = model.ToContest();
            DataManager.UpdateContest(contest);

            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Delete(int contestId)
        {
            DataManager.DeleteContestById(contestId);
            return RedirectToAction("Index");
        }
    }
}

TeamManagmentTool/Views/Contests/Create.cshtml
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@model TMT.Core.Models.Contests.ContestCreateModel

<legend>@ViewBag.ActionTitle</legend>

@using (Html.BeginForm((string)ViewBag.SubmitAction, "Contests", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <div class="form-group row">
        <div class="col-xs-2">
            @Html.LabelFor(m => m.Name, new { @class = "col-form-label" })
        </div>
        <div class="col-xs-5">
            @Html.TextBoxFor(m => m.Name, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group row">
        <div class="col-xs-2">
            @Html.LabelFor(m => m.Description, new { @class = "col-form-label" })
        </div>
        <div class="col-xs-5">
            @Html.TextBoxFor(m => m.Description, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group row">
        <div class="col-xs-2">
            @Html.LabelFor(m => m.Result, new { @class = "col-form-label" })
        </div>
        <div class="col-xs-5">
            @Html.TextBoxFor(m => m.Result, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group row">
        <div class="col-xs-2">
            @Html.LabelFor(m => m.ProblemsCount, new { @class = "col-form-label" })
        </div>
        <div class="col-xs-5">
            @Html.TextBoxFor(m => m.ProblemsCount, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group row">
        <div class="col-xs-2">
            @Html.LabelFor(m => m.Date, new { @class = "col-form-label" })
        </div>
        <div class="col-xs-2">
            <div class="input-append date form_datetime">
                <input size="16" type="text" value="@Model.Date.ToString("dd/MM/yyyy")" readonly name="Date">
                <span class="add-on"><i class="icon-th"></i></span>
            </div>
        </div>
    </div>
    @Html.HiddenFor(m => m.Id);
    @Html.HiddenFor(m => m.UserId);
    <input type="submit" class="btn btn-primary" value="Create" />
}

<script>
    $(".form_datetime").datetimepicker({
        format: "dd/MM/yyyy"
    });
</script>

TeamManagmentTool/Views/Contests/Index.cshtml
@using TMT.Core.Models
@model IEnumerable<TMT.Core.Models.Contest>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<legend>Contests</legend>

<a class="btn btn-default" href="/Contests/Create">Create contest</a>

<table class="table table-striped">
    <thead>
        <tr>
            <th>Name</th>
            <th>Description</th>
            <th>When</th>
            <th>Result</th>
            <th>Problems</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        @foreach (Contest contest in Model)
        {
            <tr>
                <td>@contest.Name</td>
                <td>@contest.Description</td>
                <td>@(((DateTime)contest.Date).ToString("dd/MM/yyyy"))</td>
                <td>@contest.Result</td>
                <td>@showProblems(contest.Problems)</td>
                <td>@Html.ActionLink("Edit", "Edit", "Contests", new { contestId = contest.Id }, new { }) | @Html.ActionLink("Delete", "Delete", "Contests", new { contestId = contest.Id }, new { })</td>
            </tr>
        }
    </tbody>
</table>

@helper showProblems(IEnumerable<Problem> problems)
{
    foreach (var problem in problems)
    {
        if (problem.Solved == false)
        {
            <span class="glyphicon glyphicon-remove"></span>
        }
        else
        {
            <span class="glyphicon glyphicon-ok"></span>
        }
    }
}