TeamManagmentTool/Controllers/ProblemsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TMT.Core.DataManagers;
using TMT.Core.Models;
using TMT.Core.Models.Problems;

namespace TeamManagmentTool.Controllers
{
    [Authorize]
    public class ProblemsController : BaseController
    {
        public ProblemsController(IDataManager dataManager)
            : base()
        {
            base.dataManager = dataManager;
        }

        public ActionResult Index(bool? solved = null)
        {
            IEnumerable<Problem> problems = DataManager.GetProblems().Where(p => solved == null || (bool)p.Solved == solved).ToList();
            ViewBag.FilterBySolved = solved;
            return View(problems);
        }
        public ActionResult Solve(int problemId)
        {
            DataManager.SolveProblem(problemId);
            return RedirectToAction("Index");
        }
        public ActionResult Unsolve(int problemId)
        {
            DataManager.UnsolveProblem(problemId);
            return RedirectToAction("Index");
        }

        public ActionResult Edit(int problemId)
        {
            Problem problem = DataManager.GetProblems().Where(p => p.Id == problemId).FirstOrDefault();
            if (problem != null)
            {
                ProblemEditModel problemEditModel = new ProblemEditModel(problem);
                return View(problemEditModel);
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult Edit(ProblemEditModel problemEditModel)
        {
            Problem problem = problemEditModel.ToProblem();
            DataManager.UpdateProblem(problem);
            return RedirectToAction("Index");
        }
    }
}

TeamManagmentTool/Views/Problems/Edit.cshtml
@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@model TMT.Core.Models.Problems.ProblemEditModel

<legend>Edit problem</legend>

@using (Html.BeginForm("Edit", "Problems", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <div class="form-group row">
        <div class="col-xs-2">
            @Html.LabelFor(m => m.ContestName, new { @class = "col-form-label" })
        </div>
        <div class="col-xs-5">
            @Html.DisplayFor(m => m.ContestName, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group row">
        <div class="col-xs-2">
            @Html.LabelFor(m => m.ProblemId, new { @class = "col-form-label" })
        </div>
        <div class="col-xs-5">
            @Html.DisplayFor(m => m.ProblemId, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group row">
        <div class="col-xs-2">
            @Html.LabelFor(m => m.Solved, new { @class = "col-form-label" })
        </div>
        <div class="col-xs-5">
            @Html.EditorFor(m => m.Solved, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group row">
        <div class="col-xs-2">
            @Html.LabelFor(m => m.Comments, new { @class = "col-form-label" })
        </div>
        <div class="col-xs-5">
            @Html.TextBoxFor(m => m.Comments, new { @class = "form-control" })
        </div>
    </div>
    @Html.HiddenFor(m => m.Id);
    @Html.HiddenFor(m => m.ContestId);
    <input type="submit" class="btn btn-primary" value="Edit" />
}

TeamManagmentTool/Views/Problems/Index.cshtml
@using TMT.Core.Models
@model IEnumerable<TMT.Core.Models.Problem>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<legend>Problems</legend>

<div class="row">
    <div class="col-xs-2">
        <select class="form-control" id="filter">
            <option value="" @Html.Raw(ViewBag.FilterBySolved == null ? "selected" : "")>All</option>
            <option value="false" @Html.Raw(ViewBag.FilterBySolved == false ? "selected" : "")>Unsolved</option>
            <option value="true" @Html.Raw(ViewBag.FilterBySolved == true ? "selected" : "")>Solved</option>
        </select>
    </div>
</div>

<table class="table table-striped">
    <thead>
        <tr>
            <th>Contest</th>
            <th>Problem</th>
            <th>Solved</th>
            <th>Comments</th>
            <th>Date</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        @foreach (Problem problem in Model)
        {
            <tr>
                <td>@problem.Contest.Name</td>
                <td>@problem.ProblemId</td>
                <td>@solvedIcon(problem.Solved)</td>
                <td>@problem.Comments</td>
                <td>@problem.Date</td>
                <td>@if (problem.Blocked != true && problem.Solved == false) {
                        @Html.ActionLink("Solve", "Solve", "Problems", new { problemId = problem.Id }, new { }) 
                    }
                    else if (problem.Blocked != true)
                    { 
                        @Html.ActionLink("Unsolve", "Unsolve", "Problems", new { problemId = problem.Id }, new { })  
                    } @Html.ActionLink("Edit", "Edit", "Problems", new { problemId = problem.Id }, new { })</td>
            </tr>
        }
    </tbody>
</table>

<script>
    $(document).ready(function () {
        var filters = $('#filter option');
        $('#filter').on("change", function () {
            filters.each(function () {
                var filter = $(this);
                if (filter.prop("selected") === true) {
                    var val = filter.val();
                    window.location.href = "/Problems?solved=" + val;
                }
            });
        });
    });
</script>

@helper solvedIcon(bool? verdict) { 
    if (verdict == false)
    {
        <span class="glyphicon glyphicon-remove"></span>
    } 
    else
    {
        <span class="glyphicon glyphicon-ok"></span>
    }
}